### ISSUE TITLE
Isseu to run the code 

### ISSUE THREAD

**Issue by gauravharjule** [DoctorKey/LSHFM.singleclassification#1]
1.Does it only require the given version to run on the PC as given in the readme
2.Fwg error is coming while running the code

Traceback (most recent call last):
  File "C:\Users\hp\Downloads\LSHFM.singleclassification-main\train_vanilla.py", line 211, in <module>
    main()
  File "C:\Users\hp\Downloads\LSHFM.singleclassification-main\train_vanilla.py", line 102, in main
    opt = parse_option()
  File "C:\Users\hp\Downloads\LSHFM.singleclassification-main\train_vanilla.py", line 88, in parse_option
    os.makedirs(opt.tb_folder)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: './save/tensorboard\\vgg13_lr_0.05_decay_0.0005_2023-10-14_17:58:03'

**Comment by DoctorKey** [comment]
I run this project on Linux. You may need to change the path in the code to run it on Windows.

**Comment by gauravharjule** [comment]
Thanks for your reply, I tried last week on linux and it worked fine

I am now able to run the code for teacher, train it but unable to get
output while running the knowledge distillation code, after the first epoch
I am getting the values as nan for losses, kd and cls.

Tried debugging it but was unable to reach the output, request please guide
for the same
*gauravharjule*

**Comment by gauravharjule** [comment]
![image](https://github.com/DoctorKey/LSHFM.singleclassification/assets/129313849/0e521391-6b62-4aa0-a841-af1da392aa89)
